In [77]:
import pandas as pd

In [78]:
url = "https://raw.githubusercontent.com/Jrtoby/General-Ledger-Financial-Analysis/main/General-Ledger.xlsx"

gl = pd.read_excel(url, sheet_name="GL", usecols=[
    "GLID", "TxnDate", "Year", "Month", "AccountNumber", "AccountName",
    "Debit", "Credit", "Dept", "CostCenter", "Description", "Currency",
    "NetAmount", "RateToUSD", "Debit_USD", "Credit_USD", "NetAmountUSD", "AccountType"
])
taux_change = pd.read_excel(url, sheet_name="ExchangeRate")

A. PRISE EN MAIN

In [79]:
gl

,GLID,TxnDate,Year,Month,AccountNumber,AccountName,Debit,Credit,Dept,CostCenter,Description,Currency,NetAmount,RateToUSD,Debit_USD,Credit_USD,NetAmountUSD,AccountType
0,GL000000,2024-05-05,2024,May,4000,Sales Revenue,0.00,2505.15,Sales,CC500,AutoPost 0,GBP,-2505.15,0.78,0.0000,1954.0170,-1954.0170,Revenue
1,GL000001,2024-06-23,2024,Jun,5000,COGS,1184.73,0.00,HR,CC500,AutoPost 1,GBP,1184.73,0.78,924.0894,0.0000,924.0894,COGS
2,GL000002,2025-01-09,2025,Jan,5000,COGS,748.25,0.00,IT,CC300,AutoPost 2,EUR,748.25,0.92,688.3900,0.0000,688.3900,COGS
3,GL000003,2023-09-30,2023,Sep,6000,Payroll Expense,1610.64,0.00,Sales,CC400,AutoPost 3,AUD,1610.64,1.51,2432.0664,0.0000,2432.0664,Expense
4,GL000004,2023-08-03,2023,Aug,5000,COGS,1053.12,0.00,HR,CC400,AutoPost 4,USD,1053.12,1.00,1053.1200,0.0000,1053.1200,COGS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,GL001995,2025-06-04,2025,Jun,5010,Travel Expense,719.33,0.00,IT,CC300,AutoPost 1995,EUR,719.33,0.92,661.7836,0.0000,661.7836,Expense
1996,GL001996,2023-08-09,2023,Aug,4000,Sales Revenue,0.00,2016.99,HR,CC400,AutoPost 1996,CAD,-2016.99,1.36,0.0000,2743.1064,-2743.1064,Revenue
1997,GL001997,2023-11-19,2023,Nov,4000,Sales Revenue,0.00,4719.37,Operations,CC100,AutoPost 1997,CAD,-4719.37,1.36,0.0000,6418.3432,-6418.3432,Revenue
1998,GL001998,2023-03-28,2023,Mar,4010,Online Sales,0.00,4523.09,Operations,CC500,AutoPost 1998,AUD,-4523.09,1.51,0.0000,6829.8659,-6829.8659,Revenue
1999,GL001999,2024-09-20,2024,Sep,4000,Sales Revenue,0.00,354.88,HR,CC500,AutoPost 1999,USD,-354.88,1.00,0.0000,354.8800,-354.8800,Revenue

In [80]:
print(gl.shape) 
print('================================')
print(taux_change)

(2000, 18)
================================
  Currency  Rate2USD
0      USD      1.00
1      GBP      0.78
2      EUR      0.92
3      AUD      1.51
4      CAD      1.36

In [81]:
gl.dtypes

GLID                     object
TxnDate          datetime64[ns]
Year                      int64
Month                    object
AccountNumber             int64
AccountName              object
Debit                   float64
Credit                  float64
Dept                     object
CostCenter               object
Description              object
Currency                 object
NetAmount               float64
RateToUSD               float64
Debit_USD               float64
Credit_USD              float64
NetAmountUSD            float64
AccountType              object
dtype: object

In [82]:
gl.isna().sum()

GLID             0
TxnDate          0
Year             0
Month            0
AccountNumber    0
AccountName      0
Debit            0
Credit           0
Dept             0
CostCenter       0
Description      0
Currency         0
NetAmount        0
RateToUSD        0
Debit_USD        0
Credit_USD       0
NetAmountUSD     0
AccountType      0
dtype: int64

In [83]:
dept = gl['Dept'].unique()
account_name = gl['AccountName'].unique()
account_type = gl['AccountType'].unique()
currency = gl['Currency'].unique()

In [84]:
print(dept)
print(account_name)
print(account_type)
print(currency)

['Sales' 'HR' 'IT' 'Marketing' 'Finance' 'Operations']
['Sales Revenue' 'COGS' 'Payroll Expense' 'Travel Expense' 'Online Sales']
['Revenue' 'COGS' 'Expense']
['GBP' 'EUR' 'AUD' 'USD' 'CAD']

B. CONTROL QUALITE ET EQUILIBRE DU GRAND LIVRE

In [85]:
gl

,GLID,TxnDate,Year,Month,AccountNumber,AccountName,Debit,Credit,Dept,CostCenter,Description,Currency,NetAmount,RateToUSD,Debit_USD,Credit_USD,NetAmountUSD,AccountType
0,GL000000,2024-05-05,2024,May,4000,Sales Revenue,0.00,2505.15,Sales,CC500,AutoPost 0,GBP,-2505.15,0.78,0.0000,1954.0170,-1954.0170,Revenue
1,GL000001,2024-06-23,2024,Jun,5000,COGS,1184.73,0.00,HR,CC500,AutoPost 1,GBP,1184.73,0.78,924.0894,0.0000,924.0894,COGS
2,GL000002,2025-01-09,2025,Jan,5000,COGS,748.25,0.00,IT,CC300,AutoPost 2,EUR,748.25,0.92,688.3900,0.0000,688.3900,COGS
3,GL000003,2023-09-30,2023,Sep,6000,Payroll Expense,1610.64,0.00,Sales,CC400,AutoPost 3,AUD,1610.64,1.51,2432.0664,0.0000,2432.0664,Expense
4,GL000004,2023-08-03,2023,Aug,5000,COGS,1053.12,0.00,HR,CC400,AutoPost 4,USD,1053.12,1.00,1053.1200,0.0000,1053.1200,COGS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,GL001995,2025-06-04,2025,Jun,5010,Travel Expense,719.33,0.00,IT,CC300,AutoPost 1995,EUR,719.33,0.92,661.7836,0.0000,661.7836,Expense
1996,GL001996,2023-08-09,2023,Aug,4000,Sales Revenue,0.00,2016.99,HR,CC400,AutoPost 1996,CAD,-2016.99,1.36,0.0000,2743.1064,-2743.1064,Revenue
1997,GL001997,2023-11-19,2023,Nov,4000,Sales Revenue,0.00,4719.37,Operations,CC100,AutoPost 1997,CAD,-4719.37,1.36,0.0000,6418.3432,-6418.3432,Revenue
1998,GL001998,2023-03-28,2023,Mar,4010,Online Sales,0.00,4523.09,Operations,CC500,AutoPost 1998,AUD,-4523.09,1.51,0.0000,6829.8659,-6829.8659,Revenue
1999,GL001999,2024-09-20,2024,Sep,4000,Sales Revenue,0.00,354.88,HR,CC500,AutoPost 1999,USD,-354.88,1.00,0.0000,354.8800,-354.8800,Revenue

In [86]:
total_debit = gl['Debit'].sum()
total_credit = gl['Credit'].sum()
ecart = total_debit - total_credit

In [87]:
print(total_debit)
print(total_credit)
print(ecart)

1210240.47
1973281.93
-763041.46

In [88]:
type = gl.groupby('AccountType')['NetAmount'].sum()

In [89]:
type

AccountType
COGS        397936.33
Expense     812304.14
Revenue   -1973281.93
Name: NetAmount, dtype: float64

In [90]:
ecart = type['Revenue'] - type['Expense'] - type['COGS']
ecart

np.float64(-3183522.4)